#!/bin/sh -xeu
set -xeu

# 1. Append the command displayed in "Step 1" (`gitlab-runner register ...`):
set -- 

# 2. Adjust OpenStack configuration:
name=scaling-runner
max_instances=10
idle_count=3
flavorRef="7e0d5c26-8e57-42ac-83fe-765fe2621fd7"
imageRef="aec88dc5-e11a-4477-afc6-4704bd06cdcf"
network_uuid="59342c0d-5f19-40c2-950b-b84cc1bcc591"

# 3. Select correct OpenStack project > Identity > Application Credentials > Create Application Credential > Download clouds.yaml:
clouds_yaml="$(
  cat <<"EOF"

EOF
)"

################################################################################

curl -fL https://github.com/emulation-as-a-service/cloud-init-update/raw/main/user-data | sh

apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y docker-compose

while [ "$#" -gt 0 ]; do case "$1" in
  --url) url="$2"; shift 2 ;;
  --token) token="$2"; shift 2 ;;
  *) shift ;;
esac; done

mkdir -p /gitlab-runner/etc

ssh-keygen -N "" -t ed25519 -f /gitlab-runner/etc/id_ed25519

cat >>/gitlab-runner/compose.yaml <<EOF
services:
  # https://docs.gitlab.com/runner/install/docker.html
  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner
    pull_policy: always
    restart: always
    entrypoint: ""
    command: sh -xeuc '/entrypoint fleeting install --upgrade; exec /usr/bin/dumb-init /entrypoint run --user=gitlab-runner --working-directory=/home/gitlab-runner'
    volumes:
      - ./etc:/etc/gitlab-runner
EOF

cat >>/gitlab-runner/etc/clouds.yaml <<EOF
$clouds_yaml
EOF

cat >>/gitlab-runner/etc/config.toml <<EOF
# https://docs.gitlab.com/runner/configuration/advanced-configuration.html
concurrent = $max_instances
check_interval = 0
shutdown_timeout = 0

[session_server]
session_timeout = 1800

[[runners]]
url = "$url"
token = "$token"
executor = "docker-autoscaler"

[runners.cache]
MaxUploadedArchiveSize = 0

[runners.docker]
tls_verify = false
image = "alpine:latest"
privileged = true
disable_entrypoint_overwrite = false
oom_kill_disable = false
disable_cache = false
volumes = ["/certs/client", "/cache"]
shm_size = 0
network_mtu = 0

[runners.autoscaler]
capacity_per_instance = 1
max_use_count = 1
max_instances = $max_instances
plugin = "ghcr.io/sardinasystems/fleeting-plugin-openstack"
update_interval = "0s"
update_interval_when_expecting = "0s"

# https://github.com/sardinasystems/fleeting-plugin-openstack#plugin-configuration
[runners.autoscaler.plugin_config]
boot_time = "10m"
cloud = "openstack"
clouds_config = "/etc/gitlab-runner/clouds.yaml"
name = "$name"

[runners.autoscaler.plugin_config.server_spec]
description = "GitLab CI Docker runners with autoscaling"
flavorRef = "$flavorRef"
name = "$name-%d"
user_data = '''
#!/bin/sh
curl -fL https://github.com/emulation-as-a-service/cloud-init-update/raw/main/user-data | sh
cat <<"END" | install -D -o debian -m 0600 /dev/stdin /home/debian/.ssh/authorized_keys
$(cat /gitlab-runner/etc/id_ed25519.pub)
END
apt-get update
apt-get install -y docker.io
usermod -aG docker debian
'''

# https://pkg.go.dev/github.com/gophercloud/gophercloud/v2/openstack/compute/v2/servers#BlockDevice
[[runners.autoscaler.plugin_config.server_spec.block_device_mapping_v2]]
source_type = "image"
uuid = "$imageRef"
delete_on_termination = true
destination_type = "volume"
volume_size = 50
disk_type = "virtio"

[[runners.autoscaler.plugin_config.server_spec.networks]]
uuid = "$network_uuid"

[runners.autoscaler.connector_config]
username = "debian"
password = ""
key_path = "/etc/gitlab-runner/id_ed25519"
use_static_credentials = true
keepalive = "30s"
timeout = "0s"
use_external_addr = false

[[runners.autoscaler.policy]]
idle_count = $idle_count
idle_time = "120m0s"
scale_factor = 3.0
scale_factor_limit = 0
EOF

$(command -v docker-compose || echo docker compose) -f /gitlab-runner/compose.yaml up -d

